[package]
name = "anime-games-launcher"
version = "1.0.0"
description = "Anime Games Launcher"
authors = ["Nikita Podvirnyy <suimin.tu.mu.ga.mi@gmail.com>"]
homepage = "https://github.com/an-anime-team/anime-games-launcher"
repository = "https://github.com/an-anime-team/anime-games-launcher"
license = "GPL-3.0"
edition = "2021"
build = "build.rs"

[profile.release]
strip = true
lto = true
opt-level = "s"

[build-dependencies]
glib-build-tools = "0.18.0"

[dependencies.relm4]
version = "0.6.1"
features = ["macros", "libadwaita"]

[dependencies.gtk]
package = "gtk4"
version = "0.6.6"
features = ["v4_10"]

[dependencies.adw]
package = "libadwaita"
version = "0.4.4"
features = ["v1_3"]

[dependencies.anime-game-core]
# git = "https://github.com/an-anime-team/anime-game-core"
# branch = "v2.0.0-rewrite"
path = "../anime-game-core"

# [dependencies.rfd]
# version = "0.11"
# features = ["xdg-portal"]
# default-features = false

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"

anyhow = { version = "1.0.75", features = ["backtrace"] }
lazy_static = "1.4.0"
flume = "0.11.0"

wincompatlib = { version = "0.7.3", features = ["all"] }
